# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Boltdbweb < Formula
  desc "Bolt DB Web UI"
  homepage "https://github.com/Isan-Rivkin/boltdbweb"
  version "1.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Isan-Rivkin/boltdbweb/releases/download/v1.0.4/boltdbweb_1.0.4_darwin_arm64.tar.gz"
      sha256 "c77e2d29b020e86b6f9cc756556efd43e76c0bc9338f7ab72e2cdc3d94e7436d"

      def install
        bin.install "boltdbweb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Isan-Rivkin/boltdbweb/releases/download/v1.0.4/boltdbweb_1.0.4_darwin_amd64.tar.gz"
      sha256 "b1629afba1ed41e0dfbc0dbffbbfb35f034056b8176d6003446398956bd714ba"

      def install
        bin.install "boltdbweb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Isan-Rivkin/boltdbweb/releases/download/v1.0.4/boltdbweb_1.0.4_linux_amd64.tar.gz"
      sha256 "404271c6b358dc2f4ce419a838ceacdd9b7e6001ac92d60f931a65ae4d43170a"

      def install
        bin.install "boltdbweb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Isan-Rivkin/boltdbweb/releases/download/v1.0.4/boltdbweb_1.0.4_linux_arm64.tar.gz"
      sha256 "35022358ffb067cf0b84a955417ad9010e17209dad298713b8bbdf0db9893157"

      def install
        bin.install "boltdbweb"
      end
    end
  end

  depends_on "git"
end
