#!/usr/bin/env bash

set -ex

brew update

echo "testing docker-machine-driver-qemu"
brew install Formula/docker-machine-driver-qemu.rb
which docker-machine-driver-qemu
/usr/local/bin/docker-machine create --driver qemu -h
echo "uninstall docker-machine-driver-qemu"
brew uninstall docker-machine-driver-qemu
